### ISSUE TITLE
Most recent update breaks syntax highlighting for BEM modifiers.

### ISSUE THREAD

**Issue by kyleatfine** [slim-template/ruby-slim.tmbundle#58]
The most recent commit merged into master breaks syntax highlighting for BEM modifier classes; that is classes that utilize the double hyphen `--` as a separator. Image attached.

<img width="542" alt="screen shot 2016-03-28 at 1 40 06 pm" src="https://cloud.githubusercontent.com/assets/5911268/14089633/b79b8df8-f4ea-11e5-8d08-1c1e70a2baff.png">

**Comment by vdv** [comment]
Create pull request for fixed with bug. https://github.com/slim-template/ruby-slim.tmbundle/pull/61
@kyleatfine Temporary you can change you local package to fix this:
- unzip .../Sublime Text 3/Installed Packages/Ruby Slim.sublime-package
- edit file Syntaxes/Ruby Slim.tmLanguage like in pull request
- restart sublime

**Comment by tshedor** [comment]
Yo @kyleatfine the Slim package was just updated - would you mind pulling the newest version and verifying that this highlights as expected?

**Comment by kyleshevlin** [comment]
This has been updated as well. I'll have to sign into my work account to close this out.

**Comment by kyleatfine** [comment]
Closing this out.
