### ISSUE TITLE
Syntax Package for Sublime Text 4107+

### ISSUE THREAD

**Issue by deathaxe** [slim-template/ruby-slim.tmbundle#84]
I've been working on a overhauled syntax definition for Sublime Text 4 (4107+).

It resolves basically all open issues of this repository for ST4 users at the time writing.

see: 
- https://github.com/deathaxe/sublime-slim/tree/st4107
- https://github.com/deathaxe/sublime-slim/tree/st4134

Syntax is basically completely rewritten based on ST4's HAML syntax using a fork of this repo as starting point. As a result the whole repo (syntax, snippets, ...) is no longer compatible with TextMate.

Hence, I'd like to re-link existing "Ruby Slim" package entry at https://packagecontrol.io to a new Sublime Text only repositry.

The idea is to keep linking to this repository for ST 2 and 3 and use a new repository as source for ST4.

My current favorite was to transfer my repository to https://github.com/SublimeText organization, so ST community can maintain it and do required changes as ST's base syntaxes move on.

Is that ok for you?

**Comment by deathaxe** [comment]
See: https://github.com/wbond/package_control_channel/pull/8669

**Comment by tshedor** [comment]
Hey @deathaxe , first, thank you heaps for doing this work. It's a lot to overhaul the syntax highlighter, and it's overdue for this repo.

I have contributing permissions on this repo and no visibility to the greater Slim org. Speaking for only myself, I support the move to the ST org because this package is relevant to ST users without adding extra features to the Slim language. 

This can cross compile to VSCode syntax highlighting, and I'll need to review how Slim is distributed as a VSCode extension. I'll report back on that soon.

Again, thank you for the effort.

**Comment by deathaxe** [comment]
Slim has been moved to https://github.com/SublimeText/Slim

**Comment by themilkman** [comment]
Maybe the decisions above would be worth a note in the Readme to avoid confusion @tshedor ?
